# Generated by Django 5.1.2 on 2024-10-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_rename_travel_travels'),
    ]

    operations = [
        migrations.AddField(
            model_name='travels',
            name='bus_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
