# Generated by Django 5.1.1 on 2024-10-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('Engine_volume', models.IntegerField()),
                ('torque', models.IntegerField()),
            ],
        ),
    ]
