# Generated by Django 5.1.1 on 2024-10-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0003_bike_milage_bike_top_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bike',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
