# Generated by Django 5.1.1 on 2024-10-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0004_student_location_alter_bike_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
